//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clout
{
    using System;
    using System.Collections.Generic;
    
    public partial class Following
    {
        public long PersonId { get; set; }
        public long FollowingId { get; set; }
    }
}
