//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clout
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public long Id { get; set; }
        public string Name { get; set; }

        public override bool Equals(object obj)
        {
            if (obj == null) return false;

            var person = obj as Person;
            if (person == null) return false;
            
            return this.Id == person.Id;
        }
    }
}
